services:
  - type: web
    name: artisan-rag-chatbot-api
    runtime: python
    repo: https://github.com/AbhishekRP2002/artisan-chatbot
    plan: free
    autoDeploy: true
    envVars:
      - key: SAMBANOVA_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: MILVUS_URI
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port $PORT

  - type: web
    name: Chainlit-Artisan-Assistant
    runtime: python
    repo: https://github.com/AbhishekRP2002/artisan-chatbot
    plan: free
    autoDeploy: true
    region: frankfurt
    buildCommand: pip install -r requirements_cl.txt
    startCommand: chainlit run src/app.py -h --port $PORT